require "../lib/gemspec_deps_gen/gemspec_deps_gen"

project_name = "sample"
version = "1.0.0"

task :gen do
  generator = GemspecDepsGen.new project_name

  generator.generate_dependencies "spec", "#{project_name}.gemspec.erb", "#{project_name}.gemspec"
end

task :build do
  system "gem build #{project_name}.gemspec"
end

task :install do
  system "gem install #{project_name}-#{version}.gem"
end

task :uninstall do
  system "gem uninstall #{project_name}"
end

task :test do
  require 'sample'

  sample = Sample.new

  puts sample.hello
end